pub mod consecutive_ones_not_allowed;
pub mod gold_mine_problem;
pub mod is_graph_a_tree;
pub mod max_sum_sub_array_of_size_k;
pub mod max_sum_without_adjacents;
pub mod painting_the_fence;
pub mod reach_the_nth_point;
pub mod strings_count;
pub mod sub_array_with_0_sum;
